title: Skullets
description: Technically Driven Comics
theme: beautiful-jekyll-theme

navbar-links:
  Comics: "skullets"
  About: "about"

collections:
  skullets:
    output: true
    permalink: /skullets/:name/

defaults:
  - scope:
      path: ""
      type: "skullets"
    values:
      layout: post

beautiful_jekyll:
  custom_css:
    - /assets/css/custom.css
